import 'package:cloud_firestore/cloud_firestore.dart';

/// A clustered accident hot-zone produced by the Cloud Function DBSCAN pass.
///
/// Written to Firestore `/hotspots/{zoneId}` every 15 minutes.
/// Read by [HotspotService] on the mobile app for driver warnings and the
/// admin heatmap overlay.
class HotspotZone {
  final String zoneId;
  final double centerLat;
  final double centerLng;

  /// Geofence radius in metres. Default cluster radius is ~300 m.
  final double radiusMeters;

  /// Total confirmed accidents + near-misses in this zone (last 90 days).
  final int incidentCount;

  /// Average severity on a 1.0 – 4.0 scale mapping to
  /// minor / moderate / severe / critical.
  final double avgSeverity;

  /// Peak hour ranges, e.g. ["08:00-09:30", "17:30-19:00"].
  final List<String> peakHours;

  /// Peak days of week, e.g. ["Monday", "Friday"].
  final List<String> peakDays;

  /// Dominant weather condition at time of incidents, e.g. "rain".
  final String weatherFactor;

  /// Trend direction over last 30 vs 60 days:
  /// `increasing`, `stable`, or `decreasing`.
  final String trend;

  /// Natural-language analysis generated by Gemini Flash.
  final String geminiAnalysis;

  /// Ambulance pre-positioning recommendation from Gemini.
  /// Keys: `recommendedStandbyPoints`, `estimatedResponseGainMinutes`, etc.
  final Map<String, dynamic> ambulanceRecommendation;

  final bool isActive;
  final DateTime lastUpdated;

  const HotspotZone({
    required this.zoneId,
    required this.centerLat,
    required this.centerLng,
    required this.radiusMeters,
    required this.incidentCount,
    required this.avgSeverity,
    required this.peakHours,
    required this.peakDays,
    required this.weatherFactor,
    required this.trend,
    required this.geminiAnalysis,
    required this.ambulanceRecommendation,
    required this.isActive,
    required this.lastUpdated,
  });

  // ── Convenience getters ─────────────────────────────────────────────

  /// Effective proximity check radius: zone radius + 500 m driver buffer.
  double get warningRadiusMeters => radiusMeters + 500.0;

  /// Severity bucket for colour coding: 1=low, 2=medium, 3=high, 4=critical.
  int get severityLevel => avgSeverity.round().clamp(1, 4);

  // ── Firestore serialization ─────────────────────────────────────────

  factory HotspotZone.fromFirestore(DocumentSnapshot doc) {
    final data = doc.data() as Map<String, dynamic>;
    return HotspotZone(
      zoneId: doc.id,
      centerLat: (data['centerLat'] as num).toDouble(),
      centerLng: (data['centerLng'] as num).toDouble(),
      radiusMeters: (data['radiusMeters'] as num).toDouble(),
      incidentCount: data['incidentCount'] as int,
      avgSeverity: (data['avgSeverity'] as num).toDouble(),
      peakHours: List<String>.from(data['peakHours'] as List? ?? []),
      peakDays: List<String>.from(data['peakDays'] as List? ?? []),
      weatherFactor: data['weatherFactor'] as String? ?? 'unknown',
      trend: data['trend'] as String? ?? 'stable',
      geminiAnalysis: data['geminiAnalysis'] as String? ?? '',
      ambulanceRecommendation: Map<String, dynamic>.from(
        data['ambulanceRecommendation'] as Map? ?? {},
      ),
      isActive: data['isActive'] as bool? ?? true,
      lastUpdated: (data['lastUpdated'] as Timestamp).toDate(),
    );
  }

  Map<String, dynamic> toFirestore() => {
        'centerLat': centerLat,
        'centerLng': centerLng,
        'radiusMeters': radiusMeters,
        'incidentCount': incidentCount,
        'avgSeverity': avgSeverity,
        'peakHours': peakHours,
        'peakDays': peakDays,
        'weatherFactor': weatherFactor,
        'trend': trend,
        'geminiAnalysis': geminiAnalysis,
        'ambulanceRecommendation': ambulanceRecommendation,
        'isActive': isActive,
        'lastUpdated': Timestamp.fromDate(lastUpdated),
      };

  Map<String, dynamic> toJson() => {
        'zoneId': zoneId,
        'centerLat': centerLat,
        'centerLng': centerLng,
        'radiusMeters': radiusMeters,
        'incidentCount': incidentCount,
        'avgSeverity': avgSeverity,
        'peakHours': peakHours,
        'peakDays': peakDays,
        'weatherFactor': weatherFactor,
        'trend': trend,
        'geminiAnalysis': geminiAnalysis,
        'ambulanceRecommendation': ambulanceRecommendation,
        'isActive': isActive,
        'lastUpdated': lastUpdated.toIso8601String(),
      };

  @override
  String toString() =>
      'HotspotZone($zoneId, incidents=$incidentCount, severity=$avgSeverity, '
      'trend=$trend)';
}
