// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE8LpX3UEK00FdzqSzuKQRm7G0aA0vYto',
    appId: '1:38653819224:web:300a6c25803800897e8d2d',
    messagingSenderId: '38653819224',
    projectId: 'ambulancetflite',
    authDomain: 'ambulancetflite.firebaseapp.com',
    storageBucket: 'ambulancetflite.firebasestorage.app',
    measurementId: 'G-KRJH2WR2CS',
  );


  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiLGeyZuGVp1n0oj7qk1oCMJ3hBxZ-q2I',
    appId: '1:38653819224:android:2800f9a987f79b7c7e8d2d',
    messagingSenderId: '38653819224',
    projectId: 'ambulancetflite',
    storageBucket: 'ambulancetflite.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOwhQQ0LNEM6-ZCfXQhGJ2lt35-ZNpntY',
    appId: '1:356551092682:ios:f8167b29317ca69c79c733',
    messagingSenderId: '356551092682',
    projectId: 'emergency-ambulance-94d91',
    storageBucket: 'emergency-ambulance-94d91.firebasestorage.app',
    databaseURL: 'https://emergency-ambulance-94d91-default-rtdb.asia-southeast1.firebasedatabase.app',
    iosBundleId: 'com.example.ambulanceServiceRespond',
  );
}
